server {
    listen 80;
    server_name _;
    client_max_body_size 100M;
    server_tokens off;

    # Serve static files directly
    location /static/ {
        alias /home/app/project/static/;
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }

    # Serve favicon.ico
    location = /favicon.ico {
        alias /home/app/project/static/public/favicon.ico;
        access_log off;
        expires 30d;
    }

    # Serve robots.txt
    location = /robots.txt {
        alias /home/app/project/static/public/robots.txt;
        access_log off;
        expires 7d;
    }

    # Forward requests to Gunicorn
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}